spring:
  profiles:
    active: ${:dev}

  data.mongodb:
    host: ${MONGODB_HOST:localhost}
    port: ${MONGODB_PORT:27017}
    database: ${MONGODB_DATABASE}
    username: ${MONGODB_USERNAME}
    password: ${MONGODB_PASSWORD}
    authentication-database: admin
application:
  stripe:
    api-key: ${STRIPE_API_KEY}